name: Aprrove
on:
   push:
    branches:
    - v3.6
   pull_request_review:
    types: [submitted, edited, dismissed]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo ${{github.event.review.state }}
