name: GitHub Pages

on:
  push:
    branches:
    - v3.6

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14
    - name: Install dependencies
      run: |
          cd user
          npm install -g @angular/cli
          npm i
          npm run test:headless
          npm run build:prod
          
    - name: Copy folder content recursively to remote
      uses: garygrossgarten/github-action-scp@release
      with:
          local: dist/angular-github-actions
          remote: ${{ secrets.SSH_PATH }}
          host: ${{ secrets.SERVER }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
          
      
  
  
    
