name: GitHub Pages
on:
  push:
    branches:
    - v3.6
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14
    - name: Install dependencies
      run: |
           npm install -g @angular/cli
           mkdir user
           cd user
           ls -la
           npm i
           npm run build:prod
           ls -la
    - name: zipping
      uses: papeloto/action-zip@v1
      with:
          files: dist/user
          dest: user.zip
    - name: Download a Deployment Zip
      uses: actions/download-artifact@v2
      with:
        name: deployment_zip
    

    
