name: GitHub Pages

on:
  push:
    branches:
    - v3.6

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14
    - name: Install dependencies
      run: |
          npm install -g @angular/cli
          npm i
          npm run test:headless
          npm run build:prod
          - name: copy file via ssh key
          uses: appleboy/scp-action@master
    
env:
          HOST:  ${{ secrets.HOST }}
          USERNAME:  ${{ secrets.USERNAME }}
          PORT:  ${{ secrets.PORT }}
          PASSWORD: ${{ secrets.PASSWORD }}
           
          source: "./dist"
          target: "/home/ubuntu/"
          strip_components: 2  
          
