name: GitHub Pages
on:
  push:
    branches:
    - v3.6
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14
    - name: Install dependencies
      run: |
           npm install -g @angular/cli
           mkdir user
           cd user
           ls -la
           npm i
           npm run build:prod
           ls -la
    - name: zipping
      uses: papeloto/action-zip@v1
      with:
          files: dist/user
          dest: user.zip
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v2
      with:
        name: user
        path: user.zip
        
  deploy_to_dev:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name != 'pull_request'
    environment: Dev
    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v2
      with:
       name: user
       run: ls -la
       uses: easingthemes/ssh-deploy@main
    env:
           SSH_PRIVATE_KEY: ${{ secrets.KEYS }}
           SOURCE: "user.zip"
           REMOTE_HOST: ${{ secrets.HOST_DNS }}
           REMOTE_USER: ${{ secrets.USERNAME }}
           TARGET: ${{ secrets.TARGET_DIR }}
        
    

    
