name: GitHub Pages
on:
  push:
    branches:
    - v3.6

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14
    - name: Install dependencies
      run: |
           npm install -g @angular/cli
           npm i
           npm run test:headless
           npm run build:prod
           ls -la
             - name: Deploy
           aws s3 sync ./dist/angular-github-actions s3://my-bucket-2022-01
           
              
           

   
          
