name: GitHub Pages

on:
  push:
    branches:
    - v3.6

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14
    - name: Install dependencies
      run: |
          npm install -g @angular/cli
          npm i
          npm run test:headless
          npm run build:prod
          - uses: actions/checkout@v2
          - name: List Files in Distribution Directory
          ls -R ./dist
          
      
  
  
    
